import pytest


#login page
def test_1(page):
    page.goto("/")
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("dev+1@easyhrworld.com")
    page.get_by_role("button", name="Continue").click()
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("r0cketInsky!")
    page.get_by_role("button", name="Sign in").click()
    
    page.wait_for_timeout(3000)
    #setting 
    page.get_by_role("button", name="KC Kanhai Chhugani").click()
    page.get_by_text("Settings").click()
    page.get_by_role("link", name="Data Master").click()
    #Branches  
    page.locator("button:nth-child(3)").click()
    page.locator("[data-test=\"name\"]").click()
    page.locator("[data-test=\"name\"]").fill("test_1")
    page.locator("[data-test=\"description\"]").click()
    page.locator("[data-test=\"description\"]").fill("mumbai ")
    page.get_by_role("button", name="Search for employee").click()
    page.get_by_role("textbox", name="Search Manager").click()
    page.get_by_role("textbox", name="Search Manager").fill("Kanhai ")
    page.get_by_text("Kanhai Chhugani (0001)").click()
    page.locator("[data-test=\"address-1\"]").click()
    page.locator("[data-test=\"address-1\"]").fill("kalyan, mumbai")
    page.locator("[data-test=\"address-2\"]").click()
    page.locator("[data-test=\"address-2\"]").click()
    page.locator("[data-test=\"address-2\"]").fill("thane, mumbai")
    page.locator("[data-test=\"city\"]").click()
    page.locator("[data-test=\"city\"]").fill("kalyan")
    page.locator("[data-test=\"country\"]").click()
    page.locator("[data-test=\"country\"]").fill("india")
    page.get_by_role("option", name="India", exact=True).click()
    page.get_by_role("button", name="Save").click()
    page.get_by_text("test_1").click()
    #self_delete
    page.get_by_role("textbox", name="Search Items").click()
    page.get_by_role("textbox", name="Search Items").press("CapsLock")
    page.get_by_role("textbox", name="Search Items").fill("test_1")
    page.get_by_text("test_1").click()
    page.get_by_role("row", name="test_1 mumbai").locator("button").click()
    page.get_by_role("menuitem", name="Delete").click()
    page.get_by_role("textbox", name="DELETE").click()
    page.get_by_role("textbox", name="DELETE").press("CapsLock")
    page.get_by_role("textbox", name="DELETE").fill("DELETE")
    page.get_by_role("button", name="Confirm").click()


   

    # Business Segments
    page.locator("li:nth-child(2) > .relative > .flex").click()
    page.locator("button:nth-child(3)").click()
    page.locator("[data-test=\"name\"]").click()
    page.locator("[data-test=\"name\"]").fill("test_1")
    page.locator("[data-test=\"description\"]").click()
    page.locator("[data-test=\"description\"]").fill("test_1")
    page.get_by_role("button", name="Save").click()
    page.get_by_role("textbox", name="Search Items").click()
    page.get_by_role("textbox", name="Search Items").fill("test_1")
    page.get_by_title("test_1").click()
    page.get_by_role("row", name="test_1 test_1").locator("button").click()
    page.get_by_role("menuitem", name="Delete").click()
    page.get_by_role("textbox", name="DELETE").click()
    page.get_by_role("textbox", name="DELETE").press("CapsLock")
    page.get_by_role("textbox", name="DELETE").press("CapsLock")
    page.get_by_role("textbox", name="DELETE").fill("DELETE")
    page.get_by_role("button", name="Confirm").click()

    #Business Verticals
   
    page.locator("li:nth-child(3) > .relative > .flex").click()
    page.locator("button:nth-child(3)").click()
    page.locator("[data-test=\"name\"]").click()
    page.locator("[data-test=\"name\"]").press("CapsLock")
    page.locator("[data-test=\"name\"]").fill("test_1")
    page.locator("[data-test=\"description\"]").click()
    page.locator("[data-test=\"description\"]").fill("test_1")
    page.get_by_role("button", name="Search for employee").click()
    page.get_by_role("textbox", name="Search Manager").click()
    page.get_by_role("textbox", name="Search Manager").fill("Kanhai")
    page.get_by_text("Kanhai Chhugani (0001)").click()
    page.get_by_role("button", name="Save").click()
    page.get_by_role("textbox", name="Search Items").click()
    page.get_by_role("textbox", name="Search Items").fill("test_1")
    page.get_by_role("cell", name="test_1").first.click()
    page.get_by_role("row", name="test_1 test_1").locator("button").click()
    page.get_by_role("menuitem", name="Delete").click()
    page.get_by_role("textbox", name="DELETE").click()
    page.get_by_role("textbox", name="DELETE").press("CapsLock")
    page.get_by_role("textbox", name="DELETE").fill("DELETE")
    page.get_by_role("button", name="Confirm").click()

    #cost centres
    page.locator("li:nth-child(4) > .relative > .flex").click()
    page.locator("button:nth-child(3)").click()
    page.locator("[data-test=\"name\"]").click()
    page.locator("[data-test=\"name\"]").fill("test_1")
    page.locator("[data-test=\"description\"]").click()
    page.locator("[data-test=\"description\"]").fill("test_1")
    page.get_by_role("button", name="Save").click()
    page.get_by_role("textbox", name="Search Items").click()
    page.get_by_role("textbox", name="Search Items").fill("test_1")
    page.get_by_role("textbox", name="Search Items").press("Enter")
    page.get_by_title("test_1").click()
    page.get_by_role("row", name="test_1 test_1").locator("button").click()
    page.get_by_role("menuitem", name="Delete").click()
    page.get_by_role("textbox", name="DELETE").click()
    page.get_by_role("textbox", name="DELETE").press("CapsLock")
    page.get_by_role("textbox", name="DELETE").fill("DELETE")
    page.get_by_role("button", name="Confirm").click()


